### ISSUE TITLE
Error on setup

### ISSUE THREAD

**Issue by themessings** [jodyalbritton/honeywell-rth6580wf#7]
Getting the following error.  Any ideas?

No signature of method: script14461227341742031108316.metadata() is applicable for argument types: (script14461227341742031108316$_run_closure2) values: [script14461227341742031108316$_run_closure2@447314de] Possible solutions: getMetadata(), getState(), setState(java.lang.Object), metaClass(groovy.lang.Closure)

**Comment by bkeifer** [comment]
You need to create a new device type, not a smartapp.

**Comment by themessings** [comment]
Thanks for the quick response.  How do I add the individual thermostats once I have the code loaded as a new device?
